version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/packages/backend"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "backend"
    groups:
      prisma:
        patterns:
          - "@prisma/*"
          - "prisma"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "npm"
    directory: "/packages/frontend"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "frontend"
