name: Bug Report
description: File a bug report for Project Pick-EM
title: "[BUG] "
labels: ["bug", "triage"]
assignees:
  - WeBeCodin
body:
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the application is affected?
      options:
        - League Management
        - User Authentication & Sessions
        - Pick System & Scoring
        - Database/Prisma
        - Frontend UI/UX
        - API/Backend Services
        - Deployment/Infrastructure
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (App unusable)
        - High (Major functionality broken)
        - Medium (Feature partially working)
        - Low (Minor issue/cosmetic)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug
      placeholder: Describe what happened and what you expected to happen
    validations:
      required: true

  - type: textarea
    id: repro-steps
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the issue
      value: |
        1. Go to...
        2. Click on...
        3. Enter...
        4. See error
    validations:
      required: true

  - type: textarea
    id: user-data
    attributes:
      label: User Session Data
      description: If this is related to league membership or authentication
      placeholder: |
        - User ID: 
        - League ID: 
        - Was user logged in? 
        - Did logout/login cycle reproduce issue?
    validations:
      required: false

  - type: textarea
    id: browser-env
    attributes:
      label: Environment
      description: Browser, device, and deployment info
      value: |
        - Browser: [e.g. Chrome 119, Safari 17]
        - Device: [e.g. Desktop, iPhone 14]
        - Deployment: [e.g. Production vercel.app, Localhost]
        - URL: [e.g. https://project-pick-em.vercel.app/leagues]
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Console errors, screenshots, or any other relevant information
      placeholder: Add any other context about the problem here
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have provided clear steps to reproduce
          required: true
        - label: This is a bug report, not a feature request
          required: true
