name: Prisma Validation

on:
  push:
    paths:
      - 'packages/backend/prisma/**'
      - 'packages/backend/package*.json'
      - '.github/workflows/prisma-validation.yml'
  pull_request:
    paths:
      - 'packages/backend/prisma/**'
      - 'packages/backend/package*.json'

jobs:
  validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm ci

      - name: Validate Prisma Schema
        run: |
          npx prisma validate
          npx prisma generate

      - name: Check Migration Status
        run: |
          npx prisma migrate status

      - name: Typecheck backend
        run: npx tsc -p tsconfig.json --noEmit
